//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPMcDonough.BAC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPMcDonough.BAC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta content=&quot;en-us&quot; http-equiv=&quot;Content-Language&quot; /&gt;
        ///&lt;meta content=&quot;text/html; charset=utf-8&quot; http-equiv=&quot;Content-Type&quot; /&gt;
        ///&lt;title&gt;SharePoint Status Report: Last Backup&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body style=&quot;font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 12px; color: #4c4c4c;&quot;&gt;
        ///
        ///&lt;h1 style=&quot;color: #000000&quot;&gt;SharePoint Sta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Send_SPBackupStatus_Status_Template {
            get {
                return ResourceManager.GetString("Send_SPBackupStatus_Status_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPBackupCatalog PipeBind object not found ({0}).
        /// </summary>
        internal static string SPBackupCatalogPipeBind_Ex_Read {
            get {
                return ResourceManager.GetString("SPBackupCatalogPipeBind_Ex_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified -ExportPath is invalid or cannot be reached.
        /// </summary>
        internal static string SPCmdletExportSPBackupCatalog_Ex_Arg1 {
            get {
                return ResourceManager.GetString("SPCmdletExportSPBackupCatalog_Ex_Arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified -ExportName contains one or more characters that are invalid for use in a file path.
        /// </summary>
        internal static string SPCmdletExportSPBackupCatalog_Ex_Arg2 {
            get {
                return ResourceManager.GetString("SPCmdletExportSPBackupCatalog_Ex_Arg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified -ExportName contains one or more characters that are invalid for use in a file name.
        /// </summary>
        internal static string SPCmdletExportSPBackupCatalog_Ex_Arg3 {
            get {
                return ResourceManager.GetString("SPCmdletExportSPBackupCatalog_Ex_Arg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The -ExcludeCount and -IncludeCount parameters cannot be used together.
        /// </summary>
        internal static string SPCmdletExportSPBackupCatalog_Ex_Arg4 {
            get {
                return ResourceManager.GetString("SPCmdletExportSPBackupCatalog_Ex_Arg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A backup export will be created that contains one or more backup sets.
        /// </summary>
        internal static string SPCmdletExportSPBackupCatalog_ShouldProcess1 {
            get {
                return ResourceManager.GetString("SPCmdletExportSPBackupCatalog_ShouldProcess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neither -RetainCount nor -RetainSize were specified.
        /// </summary>
        internal static string SPCmdletRemoveSPBackupCatalog_Ex_Arg1 {
            get {
                return ResourceManager.GetString("SPCmdletRemoveSPBackupCatalog_Ex_Arg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more backup set folders will be deleted and the spbrtoc.xml file modified.
        /// </summary>
        internal static string SPCmdletRemoveSPBackupCatalog_ShouldProcess1 {
            get {
                return ResourceManager.GetString("SPCmdletRemoveSPBackupCatalog_ShouldProcess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint Status Report: Last Backup for Catalog &quot;{0}&quot;.
        /// </summary>
        internal static string SPCmdletSendSPBackupStatus_DefaultSubject {
            get {
                return ResourceManager.GetString("SPCmdletSendSPBackupStatus_DefaultSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail containing backup status will be sent to one or more recipients.
        /// </summary>
        internal static string SPCmdletSendSPBackupStatus_ShouldProcess1 {
            get {
                return ResourceManager.GetString("SPCmdletSendSPBackupStatus_ShouldProcess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table of contents file (spbrtoc.xml) file associated with the backup catalog will be modified.
        /// </summary>
        internal static string SPCmdletSetSPBackupCatalog_ShouldProcess1 {
            get {
                return ResourceManager.GetString("SPCmdletSetSPBackupCatalog_ShouldProcess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;unavailable&gt;.
        /// </summary>
        internal static string SPGlobals_NullValue {
            get {
                return ResourceManager.GetString("SPGlobals_NullValue", resourceCulture);
            }
        }
    }
}
